# scripts are based on fits saved as "20140520.experiments.5.pt.fit.freeze.rda"
# as well as on data generated by fcs

library(nclust)
library(gdata)
library(pracma)
library(drc)
library(gplots)

source("../ALL.pipeline/scripts/pipeline.funcs.R")
source("../ALL.pipeline/scripts/dataCheckFunc.R")
source("../ALL.pipeline/scripts/fitting.functions.R")
source("../ALL.pipeline/scripts/visFuncs.R")
source("../ALL.pipeline/scripts/fitQual.funcs.R")
source("../ALL.pipeline/scripts/drug.cats.R") # --- gives objects cat and cat.1

# --- data fits, cell assay
load("./r.data.files/20140520.experiments.5.pt.fit.freeze.rda")

# --- data fits, fcs
# ========================================================================================================#
# --- Figure 1: matrix visualization, IC50 only
# ========================================================================================================#
patient.labels <- read.csv("../ALL.pipeline/data/patient.labels.csv", header=T, stringsAsFactors=F)

# --- get indices of interesting samples
integratedScoreCal(experiments.5$exp.res.mat, c("logEC50", "AUC")) -> df.int
createLabels(experiments.5$exp.res.mat, patient.labels) -> labels
gsub("fit.res.", "", rownames(df.int)) -> rownames(df.int)
mapToPatientName(df.int, patient.labels) -> df.int
setdiff(grep("a", rownames(df.int)), grep("13a", rownames(df.int))) -> ind

experiments.5$exp.res.mat$logEC90 -> curr.mat
curr.mat[ind,] -> curr.mat
gsub("fit.res.", "", rownames(curr.mat)) -> rownames(curr.mat)
mapToPatientName(curr.mat, patient.labels) -> curr.mat

# --- append fcs result for ABT-199
# dir("../ALL.pipeline/data/fcs", full.names = TRUE) -> files
# read.fcs.experiment(files) -> experiments.fcs
# fitData(experiments.fcs) -> exp.res.fcs
# averageRes(exp.res.fcs) -> exp.res.fcs.ave
# toMatrix(exp.res.ave, drug.list[,1]) -> exp.res.mat
as.data.frame(exp.res.fcs.ave) -> fcs.av

# --- first row in fit are for ABT-199
var <- "logIC50"
fcs.av[1,grep(var, colnames(fcs.av))] -> ABT.199
gsub(var, "", gsub("fit.res.", "", names(ABT.199))) -> names(ABT.199)
ABT199 <- rep(NA, nrow(curr.mat))
for (i in 1:nrow(curr.mat)){
  if (length(which(rownames(curr.mat)[i] %in% names(ABT.199))) > 0){
    ABT199[i] <- unlist(ABT.199[which(names(ABT.199) %in% rownames(curr.mat)[i])])
  }
}
cbind(curr.mat, ABT199) -> curr.mat

color.m <- matrix(data = NA, nrow = nrow(curr.mat), ncol = 1)
color.m[which(rownames(curr.mat) %in% 
                patient.labels$Short.name[which(patient.labels$Transloc %in% "t.1.19")]),] <- "blue"
color.m[which(rownames(curr.mat) %in% 
                patient.labels$Short.name[which(patient.labels$Transloc %in% "t.17.19")]),] <- "red"

nclust.clust <- nclust2(curr.mat*-1, cpwcorr=TRUE)
png("logEC50.1.19.17.19.nolab.png", w=1000, h=400)
coldmap(curr.mat*-1, clust = nclust.clust, rannot=list(color.m), 
        rdw = 5, cdw = 2, rannot.width=2, clab.height=1, rlab.width=3, cex.clab=1.5)
dev.off()

curr.mat -> logIC50.all
curr.mat -> logEC50.all
curr.mat -> AUC.all
curr.mat -> EC90.all

#plot(as.vector(AUC.all)~as.vector(EC90.all), pch=19)
#plot(as.vector(AUC.all)~as.vector(logEC50.all), pch=19)
#plot(as.vector(logEC50.all)~as.vector(EC90.all), pch=19)
#plot(as.vector(logIC50.all)~as.vector(logEC50.all), pch=19)
cor.test(as.vector(AUC.all),as.vector(EC90.all), method="s")
cor.test(as.vector(AUC.all),as.vector(logEC50.all), method="s")
cor.test(as.vector(logEC50.all),as.vector(EC90.all), method="s")
cor.test(as.vector(logEC50.all),as.vector(logIC50.all), method="s")
# ========================================================================================================#
# --- Figure 2: matrix visualization, integrated score
# ========================================================================================================#
# visMatrices(exp.res.mat, labels, 2000, 600, 3)
#as.data.frame(experiments.5$exp.res.mat) -> df
imputeNans(experiments.5$exp.res.mat) -> exp.res.mat
integratedScoreCal(exp.res.mat, c("logIC50", "logEC50", "logEC90", "AUC")) -> df.int
createLabels(experiments.5$exp.res.mat, patient.labels) -> labels
gsub("fit.res.", "", rownames(df.int)) -> rownames(df.int)
mapToPatientName(df.int, patient.labels) -> df.int

# --- keep to diagnosis only, without patient 13a
df.int[grep("a", rownames(df.int)),] -> df.int.sub
if (length(which(rownames(df.int) %in% "13a")) > 0){
  df.int.sub[-which(rownames(df.int) %in% "13a"), ] -> df.int.sub
}

as.data.frame(exp.res.fcs.ave) -> fcs.av

# --- first row in fit are for ABT-199
var <- c("AUC", "logEC90", "logEC50")
as.numeric(fcs.av[1,grep(var[1], colnames(fcs.av))]) -> ABT.199.1
as.numeric(fcs.av[1,grep(var[2], colnames(fcs.av))]) -> ABT.199.2
as.numeric(fcs.av[1,grep(var[3], colnames(fcs.av))]) -> ABT.199.3
#as.numeric(fcs.av[1,grep(var[4], colnames(fcs.av))]) -> ABT.199.4
rbind(ABT.199.1, ABT.199.2, ABT.199.3) -> ABT.199.mean
t(colMeans(ABT.199.mean)) -> ABT.199
names(ABT.199) <- names(exp.res.fcs.ave)

gsub("fit.res.", "", names(ABT.199)) -> names(ABT.199)
ABT199 <- rep(NA, nrow(df.int.sub))
for (i in 1:nrow(df.int.sub)){
  if (length(which(rownames(df.int.sub)[i] %in% names(ABT.199))) > 0){
    ABT199[i] <- unlist(ABT.199[which(names(ABT.199) %in% rownames(df.int.sub)[i])])
  }
}
cbind(df.int.sub, ABT199) -> df.int.sub

my.colors = colorRampPalette(c("red", "yellow", "green", "dark blue"))
png("integrated.score.all.1.19.17.19.wo.13a.png", w=3000, h=1500)
heatmap.2(df.int.sub,
          breaks=c(seq(-1, 0.5, length=2), seq(0.5, 1, length=4), seq(1, 3, length=10), seq(3, 4, length=10)), 
          dendrogram='both', col=my.colors,
          key=TRUE, keysize=0.5, trace="none", 
          lmat=rbind( c(0, 3), c(2,1), c(0,4) ), lhei=c(0.5, 7, 1),
          sepwidth=0.01, colsep=1:503, sepcolor='white',
          margins = c(30,30),
          scale="none",cexRow=2,cexCol=2)
dev.off()

# ========================================================================================================#
# --- Figure 3: Heat map w/o clustering
# ========================================================================================================#

# ========================================================================================================#
# --- Figure 4 to 5: Response curves
# ========================================================================================================#
read.csv("../ALL.pipeline/data/drug.list.csv", header=T, stringsAsFactors=F) -> drug.list
patient.labels <- read.csv("../ALL.pipeline/data/patient.labels.csv", header=T, stringsAsFactors=F)
patient.labels$Directory[which(patient.labels$Transloc %in% c("t.1.19", "t.17.19"))] -> names
pathways <- c("apoptosis", "cell.cycle", "ras", "clinical")

# --- go through the normalized experiments and retrieve the curves associated
# --- with a drug set
which(names(experiments.5$experiments$normalized) %in% names) -> ind
experiments.5$experiments$normalized[ind] -> normalized
df <- matrix(NA, nrow=0, ncol=242)
for (i in 1:length(normalized)){
  # --- append patient name as a column to normalized
  rep(patient.labels$Short.name[which(patient.labels$Directory %in% 
                                        names(normalized)[i])], 5) -> patient
  cbind(patient, normalized[[i]]) -> normalized[[i]]
  # -- stack contents into a df
  rbind(df, normalized[[i]]) -> df
}

# --- append transloc.type
transloc.type <- rep(NA, nrow(df))
transloc.type[which(df$patient %in% 
                      patient.labels$Short.name[which(patient.labels$Transloc %in% "t.1.19")])] <- "t.1.19"
transloc.type[which(df$patient %in% 
                      patient.labels$Short.name[which(patient.labels$Transloc %in% "t.17.19")])] <- "t.17.19"
cbind(transloc.type, df) -> df
log10(df$Concentrations) -> df$Concentrations
melt(df, id.vars = c("transloc.type", "patient", "Concentrations")) -> df

# --- append fcs data
df.fcs <- matrix(NA, nrow=0, ncol=6)
# --- create data frame of fcs.experiments
for (i in 1:length(experiments.fcs$normalized)){
  experiments.fcs$normalized[[i]] -> curr.exp
  patient.name <- rep(names(experiments.fcs$normalized)[i], nrow(curr.exp))
  cbind(patient.name, curr.exp[,1], curr.exp[,c(2:5)]) -> sub
  rbind(df.fcs, sub) -> df.fcs
}

# --- rename df.fcs columns
colnames(df.fcs) <- c("patient", "Concentrations", 
                      "ABT.199.2", "ABT.199.1",
                      "ABT-263-Navitoclax.1", "ABT-263-Navitoclax.2")

# --- append translocation information
transloc.type <- rep(NA, nrow(df.fcs))
transloc.type[which(df.fcs$patient %in% 
                      patient.labels$Short.name[which(patient.labels$Transloc %in% "t.1.19")])] <- "t.1.19"
transloc.type[which(df.fcs$patient %in% 
                      patient.labels$Short.name[which(patient.labels$Transloc %in% "t.17.19")])] <- "t.17.19"
cbind(transloc.type, df.fcs) -> df.fcs
log10(df.fcs$Concentrations) -> df.fcs$Concentrations
melt(df.fcs, id.vars = c("transloc.type", "patient", "Concentrations")) -> df.fcs
rbind(df, df.fcs) -> df

substr(as.character(df$variable), 1, nchar(as.character(df$variable))-2) -> df$variable
df$variable[grep("OBATOCLAX", df$variable)] <- "OBATOCLAX"
df$variable[grep("DMSO", df$variable)] <- "DMSO"
df$variable[grep("BEZ", df$variable)] <- "BEZ"
df$variable[grep("ABT.199", df$variable)] <- "ABT-199"
# --- lump duplicates
toupper(df$variable)-> df$variable

# use diagnosis cases only
df[grep("a", df$patient),] -> df

# --- remove sample 13
if (length(grep("13", df$patient)) > 0){
  df[-grep("13", df$patient),] -> df
}

unique(c(drug.list$pathway, drug.list$stat, drug.list$labels)) -> pathways
pathways[-which(pathways %in% "")] -> pathways
for (i in 1:length(pathways)){
  drug.list$drug[c(grep(pathways[i],drug.list$pathway),
                   grep(pathways[i],drug.list$stat),
                   grep(pathways[i],drug.list$labels))] -> pathway.drugs
  toupper(pathway.drugs) -> pathway.drugs
  row.ind <- c()
  for (j in 1:length(pathway.drugs)){
    row.ind <- c(row.ind, grep(pathway.drugs[j], df$variable))
  }
  df[row.ind,] -> df.sub
  
  scale_fill_manual(values=c("t.1.19"="cornflowerblue", "t.17.19"="salmon"))->man.fill
  scale_color_manual(values=c("t.1.19"="cornflowerblue", "t.17.19"="salmon")) -> man.color
  p <- ggplot(df.sub,aes(x=Concentrations,y=value,col=transloc.type)) +
    facet_wrap(~variable)+
    stat_summary(fun.data ="mean_sdl", mult=1, geom = "smooth", 
                 aes(fill=factor(transloc.type)), alpha=0.4)+man.fill+man.color
  ggsave(filename=paste("Resp", pathways[i],"by.type", "png", sep="."), plot=p)    
}
